Sprint2/step2 to review #1
Upr82/react-burger2 pull request #4
Opened 2024-02-11 08:05 UTC by Upr82

2024-02-11 09:14 UTC, kyzinatra commented on src/components/main/main.jsx
Можно лучше: селекторы стоит делать максимально специфичными. Так как `redux` сравнивает прошлое и новое значение возвращенное селектором просто через `===`, то стоит возвращать из селектора только то, что нам нужно, чтобы избежать лишних перерендеров
`const ingredients = useSelector(store => store.ingredients.ingredients);`
Подробнее о том, как работает `useSelector()` изнутри: https://youtu.be/SVG-x-4BQic

2024-02-11 09:15 UTC, kyzinatra commented on src/components/ingredients/burger-ingredients/burger-ingredients.jsx
> +  const mainElement = document.getElementById(MAIN);
Надо исправить: для выбора элементов стоит использовать `useRef`, если это не возможно, то получение элементов должно находится в `useEffect`, так как получение элемента является внешним эффектом и довольно долгая операция, чтобы делать ее просто так каждый рендер

2024-02-11 09:17 UTC, kyzinatra commented on src/components/ingredients/burger-ingredients/burger-ingredients.jsx
> +        setNearTitle(SAUCE);
Можно лучше: если нам больше в функции ничего не нужно, то стоит расставлять `return`, чтобы не писать лишние конструкции

```js

if (a) {
  if (b) return setA()
  return setD()
}

if (s) return setF()
return setL()

```

2024-02-11 09:18 UTC, kyzinatra commented on src/components/ingredients/ingredients-menu/ingredients-menu.jsx
>    }
Можнож лучше: передавайте в функцию реф на элемент, вместо того, чтобы каждый раз его выбирать

2024-02-11 09:18 UTC, kyzinatra commented on src/components/ingredients/ingredients-menu/ingredients-menu.jsx
Надо исправить: компонент не типизирован

2024-02-11 09:35 UTC, kyzinatra commented
Выглядит очень круто! Видно, что проделана большая работа. Но все же есть моменты на которые стоит обратить внимание.
Подробнее: 

**Что важно исправить:**

-  для выбора элементов стоит использовать `useRef`, если это не возможно, то получение элементов должно находится в `useEffect`, так как получение элемента является внешним эффектом и довольно долгая операция, чтобы делать ее просто так каждый рендер
-  компонент не типизирован


**Можно лучше:**

-  селекторы стоит делать максимально специфичными. Так как `redux` сравнивает прошлое и новое значение возвращенное селектором просто через `===`, то стоит возвращать из селектора только то, что нам нужно, чтобы избежать лишних перерендеров
`const ingredients = useSelector(store => store.ingredients.ingredients);`
Подробнее о том, как работает `useSelector()` изнутри: https://youtu.be/SVG-x-4BQic
-  если нам больше в функции ничего не нужно, то стоит расставлять `return`, чтобы не писать лишние конструкции

```js

if (a) {
  if (b) return setA()
  return setD()
}

if (s) return setF()
return setL()

```
-  передавайте в функцию реф на элемент, вместо того, чтобы каждый раз его выбирать
-  эти части верстки очень похожи. Имеет смысл вынести эти одинаковые части в отдельный компонент
-  фильтры лучше вынести в `useMemo()`
-  эту строку можно записать короче
`burgerContent.filter(item => item._id === data._id).length;`
-  можно не писать условие `allIngredients.length !== 0` если длина 0, то ничего рендерится не будет
-  обычно, если в файле нет JSX синтаксиса, то файл называют `.js`, а не `.jsx`
-  после `return` код не идет. Блоки `else` можно не ставить


**Что понравилось:**

-  Хорошая декомпозиция редьюсеров
- Отличная реализация DnD
- Хорошая верстка

**Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.**

2024-02-11 09:54 UTC, Upr82 commented on src/components/main/main.jsx
Спасибо! Исправил в двух местах.

2024-02-11 10:53 UTC, Upr82 commented on src/components/ingredients/burger-ingredients/burger-ingredients.jsx
> +  const mainElement = document.getElementById(MAIN);
Переделал на рефы и пробросил в дочерний компонент.

2024-02-11 11:05 UTC, kyzinatra requested changes
Прошу прощения, забыл апрувнуть ревью

2024-02-11 11:05 UTC, kyzinatra commented on src/components/ingredients/ingredients-container/ingredients-container.jsx
>                      data={ingredient}
Можно лучше: эти части верстки очень похожи. Имеет смысл вынести эти одинаковые части в отдельный компонент

2024-02-11 11:05 UTC, kyzinatra commented on src/components/ingredients/ingredient/ingredient.jsx
> +
Можно лучше: фильтры лучше вынести в `useMemo()`

2024-02-11 11:05 UTC, kyzinatra commented on src/components/ingredients/ingredient/ingredient.jsx
> +  const count = burgerContent.length ? burgerContent.filter(item => item._id === data._id).length : 0;
Можно лучше: эту строку можно записать короче
`burgerContent.filter(item => item._id === data._id).length;`

2024-02-11 11:05 UTC, kyzinatra commented on src/components/constructor/burger-constructor/burger-construcor.jsx
> +            if (ingredient.type !== BUN) {
Можно лучше: можно не писать условие `allIngredients.length !== 0` если длина 0, то ничего рендерится не будет

2024-02-11 11:05 UTC, kyzinatra commented on src/utils/api.jsx
> +export const postCreateOrderRequest = (ingredients) => {
Можно лучше: обычно, если в файле нет JSX синтаксиса, то файл называют `.js`, а не `.jsx`

2024-02-11 11:05 UTC, kyzinatra commented on src/services/reducers/constructor-reducer.jsx
> +      } else if (
Можно лучше: после `return` код не идет. Блоки `else` можно не ставить

2024-02-11 11:05 UTC, kyzinatra commented on src/services/reducers/root-reducer.jsx
> +  currBurger: constructorReducer,
Отлично! Хорошая декомпозиция редьюсеров

2024-02-11 12:24 UTC, Upr82 commented on src/components/ingredients/burger-ingredients/burger-ingredients.jsx
> +        setNearTitle(SAUCE);
Спасибо! Переделал.

2024-02-11 12:28 UTC, Upr82 commented on src/components/ingredients/ingredients-menu/ingredients-menu.jsx
Исправил.

2024-02-11 13:06 UTC, Upr82 commented on src/components/ingredients/ingredients-menu/ingredients-menu.jsx
>    }
Переделал на рефы.

2024-02-11 13:20 UTC, Upr82 commented on src/components/ingredients/ingredient/ingredient.jsx
> +  const count = burgerContent.length ? burgerContent.filter(item => item._id === data._id).length : 0;
Спасибо, переделал.

2024-02-11 13:21 UTC, Upr82 commented on src/utils/api.jsx
> +export const postCreateOrderRequest = (ingredients) => {
Исправил.

2024-02-11 13:24 UTC, Upr82 commented on src/services/reducers/constructor-reducer.jsx
> +      } else if (
Убрал.

2024-02-11 13:27 UTC, Upr82 commented on src/components/constructor/burger-constructor/burger-construcor.jsx
> +            if (ingredient.type !== BUN) {
Убрал

2024-02-11 13:35 UTC, Upr82 commented on src/components/ingredients/ingredient/ingredient.jsx
> +
Сделал

2024-02-12 08:01 UTC, kyzinatra commented on src/components/ingredients/burger-ingredients/burger-ingredients.jsx
> +  const mainElement = document.getElementById(MAIN);
передавайте не сам ref, а HTML элемент, если это возможно. Если нужен именно реф, то его можно описать как

```
{
current: HTMLElement | undefined
}
```

2024-02-12 08:19 UTC, merged